Validate action tag

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,9 +6,20 @@ on:
       - published
 
 jobs:
+  validate:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Validate docker image tag on action.yml file
+        run: echo "current_action_docker_tag=$(echo refs/tags/v$(grep 'image' action.yml | cut -d':' -f4 | xargs))" >> $GITHUB_ENV
+      - if: ${{ env.current_action_docker_tag != github.ref  }}
+        run: echo "::error ::Current action docker image tag '${{ env.current_action_docker_tag }}' is different from expected '${{ github.ref }}' value";exit 1
+
   release:
     runs-on: ubuntu-latest
-
+    needs:
+      - validate
+    if: ${{ success() }}
     steps:
       - uses: actions/checkout@v2
       - name: Login to DockerHub
